#angka = 10

#for angka in range (angka):
#    print(angka)


# i = 0
# while i < 6:
#     print(i)
#     i += 1
#     if i == 3:
#         break


# nama = "iqbal"

# for kalimat in nama:
#     print(kalimat)

# angka = int(input("angka: "))

# for i in range (angka):
#     if i % 2 == 0 and i != 0:
#         print(i)

# while True:
#     n = int(input("pilihan(1/2): "))

#     if n == 1:
#         print("halo")
#         break
#     elif n ==2:
#         print("hai")
#         break
#     else:
#         print("pilihan tidak valid")
#         continue

# for i in range (10):
#     pass

# print("==== PILIHAN ====")
# print("1. nomor")
# print("2. keluar")
# print("3. gwe")
# while True:
#     n = int(input("masukkan pilihan anda: "))

#     if n == 1:
#         print("oke")
#         break
#     elif n == 2:
#         print("mantap")
#         break
#     elif n == 3:
#         print("asik")
#         break
#     else:
#         print("invalid!!!!!!!")
#         continue

# Program sederhana menampilkan bilangan prima dari 1 sampai n

